### ISSUE TITLE
Repo hygiene: CMakeLists.txt serialises every test-adding PR; experiment artefacts have no size convention

### ISSUE THREAD

**Issue by atimics** [atimics/crownlesscarriage#640]
Two pieces of repo hygiene surfaced while grooming the open PR queue. Both are cheap in isolation and neither is urgent, but both compound quietly.

## 1. `CMakeLists.txt` is a structural conflict generator

Every PR that adds a test registers it at the same place — C tests as a 4–9 line `add_executable` / `target_link_libraries` / `cc_strict_warnings` / `add_test` block, Python tests as an `add_test` inside `if(CC_PYTHON3_EXECUTABLE)`. Because git sees two additions at the same position, **any two test-adding PRs conflict with each other**, structurally, regardless of what they actually change.

This is not hypothetical. It has already happened twice today:

- #615 and #619 both registered a Python integrity test at the same spot; #615 went `CONFLICTING` the moment #619 landed.
- #592 is sitting on the same conflict against `main` right now.

The fix is to stop having a single append point — per-area `.cmake` files included from the top level, or auto-discovery for the uniform cases.

**Deliberately not doing this yet.** 16 of the ~32 open PRs currently touch `CMakeLists.txt`. Refactoring it today would inject a conflict into half the open queue, including the entire 21-PR archive stack — the fix would cost more than the problem. This is worth doing when the queue is short, not now. Filing so it is not forgotten at that point.

Note the Python `add_test` calls are not uniform — some take `$<TARGET_FILE:...>` arguments and some take none — so a plain glob will not cover them without a convention for declaring the binary a test depends on.

## 2. Experiment artefacts have no size convention

`docs/experiments/` currently holds:

| Directory | Size |
|---|---|
| `simulation-baseline-2026-09-05` | 76 KB |
| `dragon-activity-2026-09-07` | 204 KB |
| `species-2026-09-08` (#615) | **4.2 MB** |

The jump is 20× the previous precedent. It is dominated by `history.csv.gz` at 2.6 MB, and by three charts committed as **both** PNG and SVG — about 857 KB of PNG alongside 440 KB of SVG for the same three figures.

`.git` is already 775 MB. Experiment directories only ever accumulate, and the sweep cadence is roughly one per day. Worth settling a convention: one vector format rather than both, and a size ceiling or a coarser sampling grid for raw history beyond which the data belongs somewhere that is not the git object store.

No change proposed to #615, which is already merged — this is about the next one.

---

## Also checked, no action needed

A fast-fail GCC job was considered and rejected: `Headless / ubuntu-latest` already builds with `GNU 13.3.0` under `-DCC_WARNINGS_AS_ERRORS=ON` and reported the recent `-Werror=format-truncation` failure in **21 seconds**. Coverage and speed are both already there.

The real gap that failure exposed is *local* reproducibility — on macOS `gcc` is Apple clang, which does not implement `-Wformat-truncation`, so the diagnostic is structurally invisible before push. A documented containerised GCC check would close that, if it ever proves worth the friction.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Kqdm5mAcAJSMrWZgPzBxDL

**Comment by atimics** [comment]
## Backlog review — 12 September 2026

Both requested improvements shipped: #683 split test registration into automatically discovered area files, and #684 established the research artifact size budget. Closing as completed.

Current dispatch: #654.
